sonar.projectKey=Terapyy18_leico
sonar.organization=terapyy18

sonar.sources=app,components,context,hooks,services,utils
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/*.stories.tsx,**/.expo/**,**/dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
